# Generated by Django 4.0.5 on 2022-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
